// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AffiliateDataContext))]
    partial class AffiliateDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.AffiliateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasMaxLength(60)
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("Date");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Product");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Seller");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Type");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Affiliates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
